# Generated by Django 3.2 on 2021-04-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.DateField(null=True),
        ),
    ]


# from mammon.money.models import *
# from datetime import date
# for x in Transaction.objects.all():
#     year = x.time.year
#     month = x.time.month
#     day = x.time.day
#     if day > 25:
#         month += 1
#         if month == 13:
#             month = 1
#             year += 1
#     x.month = date(year, month, 1)
#     x.save()
