# Generated by Django 3.2 on 2021-04-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_transaction_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date', 'description')},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='time',
            new_name='date',
        ),
    ]
