# Generated by Django 3.2 on 2021-04-24 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='auth.user', verbose_name='User')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('picture', models.ImageField(blank=True, upload_to='user-pictures', verbose_name='Picture')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, verbose_name='Gender')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('language', models.CharField(max_length=10, verbose_name='Language')),
                ('deletion_time', models.DateTimeField(blank=True, null=True, verbose_name='Deletion time')),
                ('last_notification_email_time', models.DateTimeField(blank=True, null=True, verbose_name='Notification e-mail time')),
                ('notification_style', models.CharField(choices=[('D', 'Default'), ('E', 'On every event')], default='D', max_length=10, verbose_name='Notification Style')),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_users', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_of', to='auth.group', verbose_name='Friends')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='Inviter')),
            ],
            options={
                'verbose_name': 'meta user',
                'verbose_name_plural': 'meta users',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_details', to='auth.group', verbose_name='Group')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'Details',
                'ordering': ('id',),
            },
        ),
    ]
